coverage:
  precision: 2
  round: down
  status:
    patch:                     # pull requests only: this commit status will measure the
                               # entire pull requests Coverage Diff. Checking if the lines
                               # adjusted are covered at least X%.
      default:
        enabled: yes             # must be yes|true to enable this status
        target: 90%              # specify the target "X%" coverage to hit

# comment: false  # to disable comments
comment:
  layout: "header, diff, changes, sunburst, suggestions, tree"
  behavior: default        # option: "default" posts once then update, posts new if delete
                           # option: "once"    post once then updates, if deleted do not post new
                           # option: "new"     delete old, post new
                           # option: "spammy"  post new