coverage:
  precision: 2
  round: down
  range: 95...100

comment:
  layout: "header, diff, tree, changes, sunburst"
  behavior: default
  require_changes: false
  branches: null
  flags: null
  paths: null